import {test} from 'node:test';
import assert from 'node:assert/strict';
import {connect,Store} from '../server/store.js';
import {Engine} from '../server/engine.js';
import {MockPublisher} from '../server/providers.js';
import {accountSchema,defaultSettings,id,stamp,Post,Account,validatePost,slotTime,kindAt,snapshot,Product} from '../server/domain.js';
async function fixture(){const store=new Store(await connect(true)),mock=new MockPublisher(),engine=new Engine(store,()=>mock);const a:Account={...accountSchema.parse({name:'시험 계정'}),id:id(),createdAt:stamp()};await store.put('accounts',a.id,a);await store.put('settings','main',{...defaultSettings,stopped:false});const p:Post={id:id(),accountId:a.id,date:stamp().slice(0,10),slot:0,scheduledAt:stamp(),kind:'everyday',body:'할 일을 적기 전에 책상 위 빈 공간부터 만들어 보면 어떨까요.',replies:['작은 여백에서 시작해 봐요.'],evidence:[],status:'review',issues:[],version:1,steps:[],createdAt:stamp(),updatedAt:stamp(),provider:'test',simulated:true};await engine.savePost(p);await engine.approve(p);return {store,mock,engine,a,p};}
test('중복 작업과 동시 작업자가 본문·답글을 다시 발행하지 않는다',async()=>{const f=await fixture();try{await Promise.all([f.engine.publish(f.p.id),f.engine.publish(f.p.id)]);await f.engine.publish(f.p.id);assert.equal(f.mock.calls.filter(x=>x.startsWith('publish')).length,2);assert.equal((await f.store.get<Post>('posts',f.p.id))?.status,'complete');}finally{await f.store.db.close();}});
test('본문 성공·답글 실패 후 답글만 복구한다',async()=>{const f=await fixture();try{f.mock.failAt=2;await f.engine.publish(f.p.id);assert.equal((await f.store.get<Post>('posts',f.p.id))?.status,'partial');await f.engine.publish(f.p.id);assert.equal(f.mock.calls.filter(x=>x.startsWith('create:body')).length,1);assert.equal(f.mock.calls.filter(x=>x.startsWith('publish')).length,3);assert.equal((await f.store.get<Post>('posts',f.p.id))?.status,'complete');}finally{await f.store.db.close();}});
test('응답 유실은 결과 확인 필요로 보류하고 재전송하지 않는다',async()=>{const f=await fixture();try{f.mock.loseResponse=true;await f.engine.publish(f.p.id);await f.engine.publish(f.p.id);assert.equal((await f.store.get<Post>('posts',f.p.id))?.status,'uncertain');assert.equal(f.mock.calls.filter(x=>x.startsWith('publish')).length,1);}finally{await f.store.db.close();}});
test('작업자 중단 후 sending 단계는 재전송하지 않는다',async()=>{const f=await fixture();try{f.p.status='publishing';f.p.steps[0].status='sending';await f.engine.savePost(f.p);await f.engine.publish(f.p.id);assert.equal(f.mock.calls.length,0);assert.equal((await f.store.get<Post>('posts',f.p.id))?.status,'uncertain');}finally{await f.store.db.close();}});
test('긴급 중지와 승인 후 변조를 차단한다',async()=>{const f=await fixture();try{await f.store.put('settings','main',{...defaultSettings,stopped:true});await assert.rejects(f.engine.publish(f.p.id));assert.equal(f.mock.calls.length,0);await f.store.put('settings','main',{...defaultSettings,stopped:false});f.p.body='수정한 글';await f.engine.savePost(f.p);await f.engine.publish(f.p.id);assert.equal((await f.store.get<Post>('posts',f.p.id))?.status,'blocked');assert.equal(f.mock.calls.length,0);}finally{await f.store.db.close();}});
test('지연 예약은 몰아서 게시하지 않는다',async()=>{const f=await fixture();try{await f.engine.publish(f.p.id,new Date(Date.now()+2*3600000));assert.equal((await f.store.get<Post>('posts',f.p.id))?.status,'skipped');assert.equal(f.mock.calls.length,0);}finally{await f.store.db.close();}});
test('슬롯 유일성과 예산 동시 예약 제한',async()=>{const f=await fixture();try{const reservations=await Promise.all(Array.from({length:10},()=>f.store.reserve(f.a.id,'2026-09-28',0,id())));assert.equal(reservations.filter(Boolean).length,1);await f.store.put('settings','main',{...defaultSettings,dailyCalls:1});const calls=await Promise.allSettled([f.engine.reserveCall(f.a,'gemini'),f.engine.reserveCall(f.a,'gemini')]);assert.equal(calls.filter(x=>x.status==='fulfilled').length,1);}finally{await f.store.db.close();}});
test('시간대 경계와 여러 날 비율',()=>{const a={...accountSchema.parse({name:'시간대',everydayRatio:3,affiliateRatio:1}),id:'a',createdAt:'2026-09-27T00:00:00+09:00'};assert.equal(slotTime(a,'2026-09-28',0),'2026-09-27T23:00:00.000Z');const kinds=[0,1,2,3].flatMap(d=>[0,1,2].map(s=>kindAt(a,`2026-09-${27+d}`,s)));assert.equal(kinds.filter(x=>x==='affiliate').length,3);});
test('광고 누락·계정 혼선·허위 경험·만료 상품 검사',async()=>{const f=await fixture();try{const pr:Product={id:'pr',accountId:'other',name:'제품',program:'시험',url:'https://example.com/product',source:'https://example.com/source',features:'확인한 사양',prefix:'[광고]',disclosure:'구매 시 수수료를 지급받습니다.',policyUrl:'https://example.com/policy',verified:true,verifiedAt:stamp(),validUntil:'2020-01-01',active:true,mediaType:'TEXT',mediaUrl:'',mediaRights:'',alt:''};f.p.kind='affiliate';f.p.product=pr;f.p.body='어제 내가 직접 구매했어요';const issues=validatePost(f.p,f.a,[]);assert.ok(issues.some(x=>x.includes('실제 경험')));assert.ok(issues.some(x=>x.includes('이 계정')));pr.accountId=f.a.id;assert.ok(validatePost(f.p,f.a,[]).some(x=>x.includes('광고')));assert.ok(validatePost(f.p,f.a,[]).some(x=>x.includes('유효기간')));const before=snapshot(f.p);pr.url='https://example.com/changed';assert.notEqual(snapshot(f.p),before);}finally{await f.store.db.close();}});
test('100개 계정의 슬롯을 혼선 없이 저장한다',async()=>{const store=new Store(await connect(true));try{for(let n=0;n<100;n++)for(let slot=0;slot<3;slot++)assert.ok(await store.reserve('account-'+n,'2026-09-28',slot,id()));assert.equal((await store.db.query('SELECT * FROM slots')).rows.length,300);}finally{await store.db.close();}});
