import {existsSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
if(existsSync('.env'))process.loadEnvFile('.env');
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import {DateTime} from 'luxon';
import {z} from 'zod';
import {connect,Store} from './store.js';
import {Engine} from './engine.js';
import {initializeProfiles,profileNames,ProfileName,verifyPin,changePin} from './profiles.js';
import {accountSchema,topicSchema,productSchema,settingsSchema,starterTopics,Account,Post,Product,Settings,id,stamp,slotTime,canDeletePost} from './domain.js';
const {seal,unseal,passwordHash,passwordOK}=await import('./security.js');
const {models,generate,request,ThreadsPublisher}=await import('./providers.js');
const store=new Store(await connect()),engine=new Engine(store),app=express();
if(!await store.get('migrations','subscription-v1')){const settings=await engine.settings();settings.fallback=true;settings.paidAllowed=false;await store.put('settings','main',settings);await store.put('migrations','subscription-v1',{at:stamp()});}
const port=Number(process.env.PORT||4310),host=process.env.HOST||'127.0.0.1',appUrl=process.env.APP_URL||`http://127.0.0.1:${port}`;
if(!['127.0.0.1','localhost','::1'].includes(host)&&!appUrl.startsWith('https://'))throw Error('상시 서버는 HTTPS APP_URL이 필요합니다.');
if(process.env.TRUST_PROXY==='true')app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','https:'],connectSrc:["'self'"],upgradeInsecureRequests:appUrl.startsWith('https:')?[]:null}}}));
app.use(express.json({limit:'1mb'}));
app.use('/api',(_req,res,next)=>{res.set('Cache-Control','no-store');next();});
app.use((req,res,next)=>{if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.get('origin')!==new URL(appUrl).origin)return res.status(403).json({error:'허용되지 않은 요청 출처입니다.'});next();});
await initializeProfiles(store);
const sessions=new Map<string,{expires:number;profileId:ProfileName}>();
const cookie=(req:express.Request)=>req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('studio='))?.slice(7)||'';
const activeSession=(req:express.Request)=>{const session=sessions.get(cookie(req));return session&&session.expires>Date.now()?session:undefined;};
const authenticated=(req:express.Request)=>!!activeSession(req);
const currentProfile=(req:express.Request)=>activeSession(req)!.profileId;
app.get('/api/session',async(req,res)=>res.json({profiles:profileNames,authenticated:authenticated(req),profileId:activeSession(req)?.profileId}));
const pinSchema=z.string().regex(/^\d{4}$/,'PIN은 숫자 4자리입니다.');
app.post('/api/login',rateLimit({windowMs:5*60000,limit:30,standardHeaders:true,legacyHeaders:false}),async(req,res)=>{
 const profileId=z.enum(profileNames).parse(req.body.profileId),pin=pinSchema.parse(req.body.pin),owner=id();
 if(!await store.lock('pin:'+profileId,owner))return res.status(409).json({error:'잠시 후 다시 시도하세요.'});
 try{if(!await verifyPin(store,profileId,pin))return res.status(401).json({error:'PIN이 맞지 않습니다.'});sessions.delete(cookie(req));const token=id()+id();sessions.set(token,{expires:Date.now()+12*3600000,profileId});res.cookie('studio',token,{httpOnly:true,sameSite:'strict',secure:appUrl.startsWith('https:'),maxAge:12*3600000,path:'/'});res.json({ok:true,profileId});}finally{await store.unlock('pin:'+profileId,owner);}
});
app.use('/api',(req,res,next)=>authenticated(req)?next():res.status(401).json({error:'프로필 로그인이 필요합니다.'}));
// 다른 탭에서 프로필을 바꿨다면 이전 화면의 쓰기 요청은 거부한다.
app.use('/api',(req,res,next)=>{if(req.method!=='GET'&&req.get('x-profile-id')!==currentProfile(req))return res.status(409).json({error:'프로필이 변경되었습니다. 새로고침 후 다시 진행하세요.'});next();});
async function requireAccount(req:express.Request,key:string){const a=await store.get<Account>('accounts',key);if(!a||a.profileId!==currentProfile(req))throw Error('선택한 프로필의 Threads 계정만 관리·게시할 수 있습니다.');return a;}
app.post('/api/profile/pin',async(req,res)=>{const name=currentProfile(req),owner=id();if(!await store.lock('pin:'+name,owner))throw Error('잠시 후 다시 시도하세요.');try{await changePin(store,name,pinSchema.parse(req.body.currentPin),pinSchema.parse(req.body.newPin));for(const [key,value] of sessions)if(value.profileId===name&&key!==cookie(req))sessions.delete(key);res.json({ok:true});}finally{await store.unlock('pin:'+name,owner);}});
app.post('/api/logout',(req,res)=>{sessions.delete(cookie(req));res.clearCookie('studio');res.json({ok:true});});
const publicAccount=({token,...a}:Account)=>({...a,connected:!!token});
const publicSettings=({geminiKey,openaiKey,appSecret,...s}:Settings)=>({...s,hasGemini:!!geminiKey,hasOpenai:!!openaiKey,hasAppSecret:!!appSecret});
app.get('/api/state',async(req,res)=>res.json({profileId:currentProfile(req),accounts:(await store.list<Account>('accounts')).map(publicAccount),topics:await store.list('topics'),products:await store.list('products'),posts:await store.list('posts'),settings:publicSettings(await engine.settings()),logs:await store.logs(),usage:await store.list('usage'),liveEnabled:process.env.ALLOW_LIVE_PUBLISH==='true'}));
app.post('/api/settings',async(req,res)=>{const old=await engine.settings(),s={...old,...settingsSchema.parse(req.body)};for(const k of ['geminiKey','openaiKey','appSecret'] as const){if(req.body[k])s[k]=seal(z.string().max(1000).parse(req.body[k]));}await store.put('settings','main',s);await store.log('설정 변경','생성·운영 설정 저장');res.json(publicSettings(s));});
app.post('/api/stop',async(req,res)=>{const s=await engine.settings();s.stopped=z.boolean().parse(req.body.stopped);await store.put('settings','main',s);await store.log(s.stopped?'전체 긴급 중지':'운영 재개','이미 전송된 요청은 취소되지 않습니다.');res.json({ok:true});});
app.post('/api/models',async(req,res)=>res.json(await models(z.enum(['gemini','openai']).parse(req.body.provider),await engine.settings())));
app.post('/api/model-test',async(req,res)=>{const provider=z.enum(['gemini','openai']).parse(req.body.provider);const s=await engine.settings();const a={...accountSchema.parse({name:'연결 시험'}),id:'connection-test',createdAt:stamp()};const out=await generate(provider,s,a,{id:'test',accountId:a.id,title:'책상 정리',source:'',evidence:'',verified:false,expiresAt:'',active:true,priority:1,uses:0},undefined,'',async()=>{await engine.reserveCall(a,provider);});res.json({ok:true,message:'모델 연결과 구조화 응답 검사를 통과했습니다.',model:out.model});});
app.post('/api/accounts',async(req,res)=>{const data=accountSchema.parse(req.body),key=req.body.id?z.string().parse(req.body.id):id(),old=await store.get<Account>('accounts',key);if(old)await requireAccount(req,key);if(data.live&&!old?.token)throw Error('먼저 Threads 계정을 연결하세요.');const a:Account={...old,...data,id:key,profileId:currentProfile(req),createdAt:old?.createdAt||stamp()};await store.put('accounts',key,a);if(!old)for(const title of starterTopics){const t={...topicSchema.parse({accountId:key,title}),id:id(),uses:0};await store.put('topics',t.id,t);}await store.log('계정 저장',a.name,key);res.json(publicAccount(a));});
app.post('/api/accounts/:id/disconnect',async(req,res)=>{const a=await requireAccount(req,req.params.id);if(!a)throw Error('계정이 없습니다.');delete a.token;delete a.threadsId;delete a.username;delete a.expiresAt;a.paused=true;a.live=false;await store.put('accounts',a.id,a);await store.log('계정 연결 해제',a.name,a.id);res.json({ok:true});});
app.post('/api/topics',async(req,res)=>{const data=topicSchema.parse(req.body);if(!await store.get('accounts',data.accountId))throw Error('계정이 없습니다.');const key=req.body.id||id(),old=await store.get<any>('topics',key);if(old&&old.accountId!==data.accountId)throw Error('계정 변경은 허용되지 않습니다.');const t={...old,...data,id:key,uses:old?.uses||0};await store.put('topics',key,t);res.json(t);});
app.post('/api/products',async(req,res)=>{const data=productSchema.parse(req.body);if(!await store.get('accounts',data.accountId))throw Error('계정이 없습니다.');if(!Number.isFinite(Date.parse(data.validUntil))||!Number.isFinite(Date.parse(data.verifiedAt)))throw Error('확인일과 만료일을 입력하세요.');const key=req.body.id||id(),old=await store.get<Product>('products',key);if(old&&old.accountId!==data.accountId)throw Error('상품 계정을 변경할 수 없습니다.');const p={...data,id:key};await store.put('products',key,p);await store.log('상품 저장',p.name,p.accountId);res.json(p);});
app.post('/api/plan',async(req,res)=>{const a=await requireAccount(req,z.string().parse(req.body.accountId));if(!a)throw Error('계정을 선택하세요.');const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(req.body.date),days=z.number().int().min(1).max(3).parse(req.body.days||1);const result=[];for(let i=0;i<days;i++)result.push(...await engine.plan(a,DateTime.fromISO(date).plus({days:i}).toISODate()!));res.json(result);});
app.post('/api/import',async(req,res)=>{const a=await requireAccount(req,z.string().parse(req.body.accountId));if(!a)throw Error('계정을 선택하세요.');const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(req.body.date);const items=z.array(z.object({body:z.string().min(1).max(500),replies:z.array(z.string().max(500)).max(3).default([]),productId:z.string().optional()})).min(1).max(90).parse(req.body.items);let count=0;for(let i=0;i<items.length;i++){const day=DateTime.fromISO(date).plus({days:Math.floor(i/3)}).toISODate()!,slot=i%3,item=items[i],pr=item.productId?await store.get<Product>('products',item.productId):undefined;if(item.productId&&(!pr||pr.accountId!==a.id))throw Error('해당 계정의 상품이 아닙니다.');const p:Post={id:id(),accountId:a.id,date:day,slot,scheduledAt:slotTime(a,day,slot),kind:pr?'affiliate':'everyday',body:pr?pr.prefix+'\n'+item.body:item.body,replies:pr?[`${pr.disclosure}\n${item.replies[0]||''}\n${pr.url}`,...item.replies.slice(1)]:item.replies,product:pr,evidence:pr?[pr.features]:a.facts?[a.facts]:[],status:'review',issues:[],version:1,steps:[],createdAt:stamp(),updatedAt:stamp(),provider:'직접 등록',simulated:!a.live};if(await store.reservePost(p)){count++;}}res.json({count});});
app.post('/api/posts/:id/action',async(req,res)=>{const key=req.params.id,owner=id();if(!await store.lock('publish:'+key,owner))throw Error('발행 작업 중입니다. 잠시 후 다시 시도하세요.');try{const p=await store.get<Post>('posts',key);if(!p)throw Error('글이 없습니다.');await requireAccount(req,p.accountId);const action=z.enum(['approve','hold','cancel','edit','retry','reconcile','delete']).parse(req.body.action);if(p.status==='publishing')throw Error('발행 중인 글은 수정할 수 없습니다.');if(p.steps.some(s=>['sending','creating','uncertain'].includes(s.status))&&action!=='reconcile')throw Error('결과가 불확실한 작업은 확인 외의 상태 변경을 할 수 없습니다.');if(action==='reconcile'){
 if(p.status!=='uncertain')throw Error('결과 확인 필요 상태가 아닙니다.');const a=await store.get<Account>('accounts',p.accountId);if(!a?.token)throw Error('실제 계정 연결이 필요합니다.');const step=p.steps.find(s=>s.status==='uncertain');if(!step?.containerId)throw Error('컨테이너 ID가 없어 자동 확인할 수 없습니다. 보류 상태를 유지하세요.');const state=await new ThreadsPublisher(a).status(step.containerId);p.error=`컨테이너 상태: ${state}. 게시 ID까지 확정되지 않아 재전송을 차단합니다.`;await engine.savePost(p);
 }else if(action==='delete'){
 // 게시 이력이 있거나 예약·생성 진행 중인 글은 기록과 슬롯을 지키기 위해 삭제하지 않는다.
 if(!canDeletePost(p))throw Error(p.steps.some(s=>s.postId)?'게시 이력이 있는 글은 삭제할 수 없습니다.':'검토 대기·검증 실패·보류·취소된 글만 삭제할 수 있습니다. 예약된 글은 먼저 취소하세요.');await store.removePost(p.id);
 }else if(action==='approve'){if(p.steps.some(s=>s.postId)||p.status==='uncertain')throw Error('게시 이력이 있는 글은 재승인할 수 없습니다.');await engine.approve(p);}
 else if(action==='retry'){if(!['held','partial'].includes(p.status)||p.steps.some(s=>['uncertain','sending','creating'].includes(s.status)))throw Error('결과가 불확실한 작업은 재전송할 수 없습니다.');if(!p.approvedHash)throw Error('먼저 내용을 검토하고 승인하세요.');p.status=p.steps[0]?.postId?'partial':'scheduled';p.nextAttempt=stamp();await engine.savePost(p);}
 else if(action==='edit'){if(p.steps.some(s=>s.postId)||p.status==='uncertain')throw Error('게시된 글은 수정할 수 없습니다.');await store.put('versions',id(),{postId:p.id,version:p.version,body:p.body,replies:p.replies,at:stamp()});p.body=z.string().min(1).max(500).parse(req.body.body);p.replies=z.array(z.string().max(500)).max(3).parse(req.body.replies);p.version++;p.approvedHash=undefined;p.steps=[];p.status='review';p.issues=[];await engine.savePost(p);}
 else{p.status=action==='hold'?'held':'cancelled';await engine.savePost(p);}await store.log('콘텐츠 변경',`${p.id}: ${action}`,p.accountId);res.json(p);}finally{await store.unlock('publish:'+key,owner);}});
app.post('/api/simulate/:id',async(req,res)=>{const p=await store.get<Post>('posts',req.params.id);if(!p||!p.simulated)throw Error('모의 게시 글만 시험할 수 있습니다.');await requireAccount(req,p.accountId);if(Date.parse(p.scheduledAt)>Date.now())throw Error('예약 시간이 되어야 처리됩니다.');await engine.publish(p.id);res.json({ok:true});});
app.post('/api/oauth/start',async(req,res)=>{const a=await requireAccount(req,z.string().parse(req.body.accountId)),s=await engine.settings();if(!a||!s.appId||!s.appSecret)throw Error('계정과 Threads 앱 ID·시크릿을 먼저 설정하세요.');const state=id()+id();await store.put('oauth',state,{accountId:a.id,expires:Date.now()+600000,session:cookie(req)});const q=new URLSearchParams({client_id:s.appId,redirect_uri:appUrl+'/oauth/callback',scope:'threads_basic,threads_content_publish',response_type:'code',state});res.json({url:'https://threads.net/oauth/authorize?'+q});});
app.get('/oauth/callback',async(req,res)=>{try{const state=String(req.query.state||''),pending=await store.get<any>('oauth',state);if(!pending||pending.expires<Date.now()||pending.session!==cookie(req)||!authenticated(req))throw Error('OAuth 요청이 만료되었거나 일치하지 않습니다.');await store.remove('oauth',state);const s=await engine.settings();const q=new URLSearchParams({client_id:s.appId,client_secret:unseal(s.appSecret),grant_type:'authorization_code',redirect_uri:appUrl+'/oauth/callback',code:z.string().parse(req.query.code)});const short=await request('https://graph.threads.net/oauth/access_token',{method:'POST',body:q});const long=await request('https://graph.threads.net/access_token?'+new URLSearchParams({grant_type:'th_exchange_token',client_secret:unseal(s.appSecret),access_token:short.access_token}));const me=await request('https://graph.threads.net/v1.0/me?'+new URLSearchParams({fields:'id,username',access_token:long.access_token}));const a=await requireAccount(req,pending.accountId);if(!a)throw Error('계정이 없습니다.');if((await store.list<Account>('accounts')).some(x=>x.id!==a.id&&x.threadsId===me.id))throw Error('이미 다른 운영 계정에 연결된 Threads 계정입니다.');a.token=seal(long.access_token);a.threadsId=me.id;a.username=me.username;a.expiresAt=new Date(Date.now()+long.expires_in*1000).toISOString();await store.put('accounts',a.id,a);await store.log('Threads 연결',a.name,a.id);res.redirect('/');}catch{res.status(400).type('text').send('Threads 연결에 실패했습니다. 앱 설정·권한·리디렉션 주소를 확인하고 다시 연결하세요.');}});
app.post('/api/accounts/:id/refresh',async(req,res)=>{const a=await requireAccount(req,req.params.id);if(!a?.token)throw Error('계정을 연결하세요.');const r=await request('https://graph.threads.net/refresh_access_token?'+new URLSearchParams({grant_type:'th_refresh_token',access_token:unseal(a.token)}));a.token=seal(r.access_token);a.expiresAt=new Date(Date.now()+r.expires_in*1000).toISOString();await store.put('accounts',a.id,a);res.json({ok:true});});
app.use('/api',(_req,res)=>res.status(404).json({error:'지원하지 않는 요청입니다.'}));
app.use(express.static(resolve('dist')));app.get('/{*path}',(_req,res)=>res.sendFile(resolve('dist/index.html')));
app.use((err:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{res.status(400).json({error:err instanceof z.ZodError?'입력값을 확인하세요: '+err.issues.map(x=>x.path.join('.')+' '+x.message).join(' / '):err.message||'요청 처리에 실패했습니다.'});});
const server=app.listen(port,host,()=>console.log(`Threads Studio: ${appUrl}`));
const timer=setInterval(()=>engine.tick().catch(()=>{}),15000);
async function shutdown(){clearInterval(timer);server.close();await store.db.close();process.exit(0);}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
