import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';

// 공식 CLI에 인증을 맡긴다. 저장된 OAuth 토큰을 읽거나 앱 DB로 복사하지 않는다.
export function subscriptionEnv(){const env:NodeJS.ProcessEnv={};for(const name of ['PATH','Path','PATHEXT','SystemRoot','WINDIR','TEMP','TMP','USERPROFILE','HOME','APPDATA','LOCALAPPDATA','CODEX_HOME'])if(process.env[name])env[name]=process.env[name];return env;}
function invoke(args:string[],input='',cwd?:string,timeout=180000){return new Promise<string>((resolve,reject)=>{const child=spawn(process.env.CODEX_BINARY||'codex',args,{shell:false,windowsHide:true,cwd,env:subscriptionEnv(),stdio:['pipe','pipe','pipe']});let output='',done=false;const finish=(error?:Error)=>{if(done)return;done=true;clearTimeout(timer);error?reject(error):resolve(output);};const timer=setTimeout(()=>{child.kill();finish(Error('구독 생성 시간이 초과되었습니다. 글 생성만 보류합니다.'));},timeout);child.on('error',()=>finish(Error('Codex CLI를 실행할 수 없습니다. 설치 경로와 ChatGPT 로그인을 확인하세요.')));for(const stream of [child.stdout,child.stderr])stream.on('data',b=>{output+=String(b);if(output.length>2000000){child.kill();finish(Error('CLI 출력 제한을 초과했습니다.'));}});child.on('close',code=>finish(code===0?undefined:Error('Codex 구독 요청이 실패했습니다. 로그인·구독 한도·모델을 확인하세요. API로 전환하지 않습니다.')));child.stdin.on('error',()=>{});child.stdin.end(input);});}
export async function subscriptionStatus(){const result=await invoke(['login','status'],'',undefined,15000);if(!/logged in using chatgpt/i.test(result))throw Error('ChatGPT 구독 로그인이 필요합니다. 터미널에서 codex login을 실행하세요. API 키 로그인은 사용하지 않습니다.');return {ok:true,message:'ChatGPT 구독 로그인 확인 완료'};}
export async function subscriptionGenerate(prompt:string,schema:unknown,model:string){await subscriptionStatus();if(model&&!/^[\w.:-]+$/.test(model))throw Error('모델 ID를 확인하세요.');const dir=await mkdtemp(join(tmpdir(),'threads-writing-'));try{const output=join(dir,'result.json'),schemaPath=join(dir,'schema.json');await writeFile(schemaPath,JSON.stringify(schema));const args=['exec','--ignore-user-config','--ephemeral','--skip-git-repo-check','--sandbox','read-only','-c','forced_login_method="chatgpt"','-c','model_provider="openai"','--output-schema',schemaPath,'--output-last-message',output,'--color','never'];if(model)args.push('--model',model);args.push('-');await invoke(args,'글 작성만 수행하세요. 도구 실행, 파일 탐색, 네트워크 접근은 하지 마세요. 아래 자료만으로 JSON을 반환하세요.\n'+prompt,dir);return await readFile(output,'utf8');}finally{await rm(dir,{recursive:true,force:true});}}
