import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,CalendarDays,FileText,Package,Lightbulb,Settings,Activity,Plus,ArrowUpRight,Pause,Play,Check,ArrowRight,LogOut,Sparkles,ShieldCheck} from 'lucide-react';
import './style.css';
type Data=Record<string,any>;
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error||'요청에 실패했습니다.');return value;}
const labels:Data={review:'검토 대기',blocked:'검증 실패',scheduled:'예약 완료',publishing:'발행 중',partial:'답글 미완료',complete:'전체 완료',uncertain:'결과 확인 필요',held:'보류',cancelled:'취소',skipped:'건너뜀'};
const nav=[['dashboard','대시보드',LayoutDashboard],['posts','콘텐츠 검토',FileText],['calendar','예약 일정',CalendarDays],['accounts','계정 관리',Users],['topics','주제 보관함',Lightbulb],['products','상품 · 제휴 링크',Package],['logs','발행 기록',Activity],['settings','연결 및 설정',Settings]] as const;
const dateTomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(d);};
function App(){
 const [session,setSession]=useState<Data|null>(null),[data,setData]=useState<Data|null>(null),[page,setPage]=useState('dashboard'),[filter,setFilter]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<Data|null>(null),[modelList,setModelList]=useState<string[]>([]);
 const refresh=async()=>setData(await api('state'));
 useEffect(()=>{api('session').then(async s=>{setSession(s);if(s.authenticated)await refresh();}).catch(e=>setNotice(e.message));},[]);
 useEffect(()=>{if(!session?.authenticated)return;const timer=setInterval(()=>refresh().catch(()=>{}),15000);return()=>clearInterval(timer);},[session?.authenticated]);
 async function run(fn:()=>Promise<any>,message='저장했습니다.'){setBusy(true);setNotice('');try{await fn();await refresh();if(message)setNotice(message);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 const field=(label:string,key:string,type='text',extra:Data={})=><label className="field">{label}{type==='textarea'?<textarea value={modal?.[key]??''} onChange={e=>setModal({...modal,[key]:e.target.value})} {...extra}/>:type==='checkbox'?<input type="checkbox" checked={!!modal?.[key]} onChange={e=>setModal({...modal,[key]:e.target.checked})}/>:<input type={type} value={modal?.[key]??''} onChange={e=>setModal({...modal,[key]:type==='number'?Number(e.target.value):e.target.value})} {...extra}/>}</label>;
 const selectAccount=()=> <label className="field">운영 계정<select required value={modal?.accountId||''} onChange={e=>setModal({...modal,accountId:e.target.value})}><option value="">계정 선택</option>{data?.accounts.map((a:Data)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>;
 const accountName=(id:string)=>data?.accounts.find((a:Data)=>a.id===id)?.name||'계정';
 const openAccount=(a:Data={})=>setModal({type:'account',name:'',theme:'생활 속 작은 관찰',audience:'일상을 편하게 만들고 싶은 사람',tone:'친구에게 이야기하듯 자연스러운 존댓말',facts:'',banned:'무조건,역대급,최저가,품절 임박',timesText:'08:00,12:30,21:30',timezone:'Asia/Seoul',everydayRatio:2,affiliateRatio:1,warmupDays:0,productInterval:14,dailyCalls:12,graceMinutes:30,auto:false,paused:false,live:false,fallbackEveryday:true,...a,...(a.times?{timesText:a.times.join(',')}:{})});
 const openPlan=()=>setModal({type:'plan',accountId:filter||data?.accounts[0]?.id||'',date:dateTomorrow(),days:1});
 const openProduct=(p:Data={})=>setModal({type:'product',accountId:filter||data?.accounts[0]?.id||'',name:'',program:'',url:'',source:'',features:'',disclosure:'',prefix:'[광고]',policyUrl:'',verified:false,verifiedAt:new Date().toISOString().slice(0,10),validUntil:dateTomorrow(),active:true,mediaType:'TEXT',mediaUrl:'',mediaRights:'',alt:'',...p});
 async function submit(e:React.FormEvent){e.preventDefault();if(!modal)return;await run(async()=>{const m=modal;if(m.type==='account')await api('accounts',{...m,times:m.timesText.split(',').map((x:string)=>x.trim())});if(m.type==='product')await api('products',m);if(m.type==='topic')await api('topics',m);if(m.type==='plan'){const r=await api('plan',m);if(r.some((x:Data)=>x.error))throw Error(r.find((x:Data)=>x.error).error);}
 if(m.type==='import'){let items;if(m.format==='json')items=JSON.parse(m.content);else items=m.content.split(/\n\s*---\s*\n/).filter((x:string)=>x.trim()).map((body:string)=>({body:body.trim(),replies:[]}));const r=await api('import',{...m,items});if(!r.count)throw Error('선택한 날짜의 예약 슬롯이 이미 사용 중입니다.');}
 if(m.type==='edit')await api(`posts/${m.id}/action`,{action:'edit',body:m.body,replies:m.replyText?m.replyText.split('\n---\n'):[]});
 if(m.type==='settings')await api('settings',m);setModal(null);});}
 if(!session)return <div className="loading">Threads Studio를 열고 있습니다…{notice}</div>;
 if(!session.authenticated)return <div className="login"><div className="login-art"><div className="wordmark">◉ THREADS STUDIO</div><h1>좋은 글을 쌓고,<br/>꾸준한 연결을 만들다.</h1><p>소재부터 예약 게시까지.<br/>여러 계정의 하루를 한곳에서 운영하세요.</p><span className="login-note">Gemini 우선 · GPT 대체 · 공식 Threads API</span></div><form className="login-form" onSubmit={async e=>{e.preventDefault();const password=new FormData(e.currentTarget).get('password');setBusy(true);try{await api('login',{password});setSession({authenticated:true});await refresh();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}><div className="eyebrow">YOUR CONTENT WORKSPACE</div><h2>{session.setup?'작업실을 시작하세요':'다시 오셨네요'}</h2><p>{session.setup?'이 PC의 관리자 비밀번호를 설정합니다.':'관리자 비밀번호로 로그인하세요.'}</p><label className="field">비밀번호<input name="password" type="password" minLength={12} required autoComplete={session.setup?'new-password':'current-password'} placeholder="12자 이상"/></label><button className="primary" disabled={busy}>{session.setup?'설정하고 시작하기':'로그인'} <ArrowRight size={17}/></button>{notice&&<p role="alert" className="notice">{notice}</p>}<small>비밀번호와 API 키는 채팅에 입력하지 마세요.</small></form></div>;
 if(!data)return <div className="loading">운영 정보를 불러오고 있습니다…</div>;
 const posts=data.posts.filter((p:Data)=>!filter||p.accountId===filter).sort((a:Data,b:Data)=>a.scheduledAt.localeCompare(b.scheduledAt));
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());const todayPosts=posts.filter((p:Data)=>p.date===today);const issues=posts.filter((p:Data)=>['blocked','held','uncertain','partial'].includes(p.status));
 const card=(p:Data)=><article className="post-card" key={p.id}><div className="row"><span className="avatar">{accountName(p.accountId).slice(0,1)}</span><div><strong>{accountName(p.accountId)}</strong><small>{p.date} · {new Date(p.scheduledAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</small></div><span className={'badge '+p.status}>{labels[p.status]}</span></div><div className="post-body">{p.body||'글 생성이 보류되었습니다.'}</div>{p.replies.map((r:string,i:number)=><div className="reply" key={i}><small>↳ 자기 답글 {i+1}</small><p>{r}</p></div>)}{p.product?.mediaUrl&&<a href={p.product.mediaUrl} target="_blank" rel="noreferrer" className="link">등록 미디어 확인 ↗</a>}{(p.error||p.issues?.length>0)&&<div className="warning">{p.error||p.issues.join(' / ')}</div>}<div className="post-meta"><span>{p.kind==='affiliate'?'제휴 콘텐츠':'일상 콘텐츠'} · {p.simulated?'모의 발행':'실제 발행'}</span><span>v{p.version} · {p.provider}</span></div><details><summary>근거와 단계별 결과</summary><p>{p.evidence.join('\n')||'등록 근거 없음 · 일반 관찰형 글만 허용'}</p>{p.brief&&<p>{Object.values(p.brief).join(' · ')}</p>}{p.steps.map((s:Data,i:number)=><p key={s.key}>{i===0?'본문':'답글 '+i}: {s.postId||s.status} {s.permalink&&<a href={s.permalink} target="_blank" rel="noreferrer">게시물 보기 ↗</a>}</p>)}</details><div className="actions">{['review','blocked'].includes(p.status)&&<><button className="primary small" disabled={busy} onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'approve'}),'검증 후 예약했습니다.')}><Check size={15}/>승인 · 예약</button><button onClick={()=>setModal({...p,type:'edit',replyText:p.replies.join('\n---\n')})}>수정</button></>}{['held','partial'].includes(p.status)&&p.approvedHash&&<button onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'retry'}))}>남은 단계 재시도</button>}{p.status==='uncertain'&&<button onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'reconcile'}),'결과 확인 상태를 갱신했습니다.')}>게시 결과 확인</button>}{!['complete','cancelled','publishing','uncertain'].includes(p.status)&&<button onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'hold'}))}>보류</button>}{!['complete','cancelled','publishing','uncertain'].includes(p.status)&&<button className="text-button" onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'cancel'}))}>취소</button>}</div></article>;
 return <div className="shell"><aside><div className="brand"><span>◉</span><div>Threads<span>STUDIO</span></div></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}><Icon size={19}/>{label}{key==='posts'&&<b>{data.posts.filter((p:Data)=>p.status==='review').length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="engine-label"><Sparkles size={17}/><span>Gemini 우선 생성<small>{data.settings.fallback?'GPT 대체 경로 활성':'GPT 대체 경로 미설정'}</small></span></div><button className="logout" onClick={async()=>{await api('logout',{});setSession({authenticated:false});}}><LogOut size={16}/>로그아웃</button></div></aside><main><header><div className="breadcrumb">작업실 <span>/</span> {nav.find(x=>x[0]===page)?.[1]}</div><div className="header-right"><span className="mode-label">{data.settings.stopped?'발행 중지됨':'예약 처리 중'}</span><button className={data.settings.stopped?'resume':'stop'} disabled={busy} onClick={()=>run(()=>api('stop',{stopped:!data.settings.stopped}),data.settings.stopped?'운영을 재개했습니다.':'신규 발행을 중지했습니다.')} >{data.settings.stopped?<Play size={15}/>:<Pause size={15}/>} {data.settings.stopped?'운영 재개':'전체 중지'}</button></div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">{page==='dashboard'?'CONTENT, ON YOUR TERMS.':'THREADS STUDIO'}</div><h1>{page==='dashboard'?'오늘의 작업실':nav.find(x=>x[0]===page)?.[1]}</h1><p>{page==='dashboard'?'계정의 하루를 살펴보고, 다음 이야기를 준비하세요.':page==='posts'?'본문과 답글, 사용한 근거를 함께 확인하세요.':page==='settings'?'API 키와 모델을 설정하고 연결을 시험하세요.':'계정별 운영 정보를 관리하세요.'}</p></div><div className="heading-actions"><select aria-label="계정 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">모든 계정</option>{data.accounts.map((a:Data)=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{['dashboard','posts','calendar'].includes(page)&&<button className="primary" onClick={openPlan}><Sparkles size={16}/>글 생성 · 예약 준비</button>}</div></div>{notice&&<div role="status" className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}{busy&&<div className="busy" role="status">처리 중입니다. 생성은 잠시 걸릴 수 있습니다…</div>}
 {page==='dashboard'&&<><div className="metrics">{[['오늘 예정',todayPosts.length,'하루 본문 기준'],['본문 게시',todayPosts.filter((p:Data)=>p.steps[0]?.postId).length,'모의 / 실제 표시는 글별 확인'],['전체 완료',todayPosts.filter((p:Data)=>p.status==='complete').length,'답글까지 처리 완료'],['확인할 항목',issues.length,'검증 · 연결 · 생성 문제']].map(([label,n,sub],i)=><section className={'metric m'+i} key={label}><span>{label}</span><strong>{String(n).padStart(2,'0')}<small>건</small></strong><p>{sub}</p></section>)}</div><div className="dashboard-grid"><section className="panel"><div className="section-heading"><h2>다음 발행 일정</h2><button className="text-button" onClick={()=>setPage('calendar')}>전체 일정 <ArrowUpRight size={16}/></button></div>{posts.filter((p:Data)=>!['complete','cancelled','skipped'].includes(p.status)).slice(0,5).map((p:Data)=><div className="schedule-row" key={p.id}><div className="schedule-time">{new Date(p.scheduledAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false})}<small>{p.date.slice(5)}</small></div><div><strong>{p.body?.slice(0,42)||'생성 대기 · '+accountName(p.accountId)}</strong><small>{accountName(p.accountId)} · {p.kind==='affiliate'?'제휴':'일상'} · {p.simulated?'모의':'실제'}</small></div><span className={'badge '+p.status}>{labels[p.status]}</span></div>)}{!posts.length&&<div className="empty"><CalendarDays size={32}/><h3>첫 번째 이야기를 준비해 볼까요?</h3><p>계정을 추가하고 주제를 정하면<br/>다음 날의 글을 미리 준비할 수 있어요.</p><button onClick={()=>openAccount()}><Plus size={16}/>계정 추가</button></div>}</section><section className="setup-panel"><span className="eyebrow">READY WHEN YOU ARE</span><h2>자동화 준비</h2>{[[data.accounts.length>0,'운영 계정 등록','주제 · 말투 · 게시 시간'],[data.settings.hasGemini&&data.settings.geminiModel,'Gemini 연결','API 키 저장 · 모델 시험'],[data.accounts.some((a:Data)=>a.connected),'Threads 계정 연결','공식 로그인과 게시 권한'],[data.posts.some((p:Data)=>p.status==='scheduled'),'콘텐츠 검토','근거 확인 후 승인']].map(([ok,title,desc],i)=><div className="setup-step" key={String(title)}><span className={ok?'done':''}>{ok?<Check size={16}/>:i+1}</span><div><strong>{title}</strong><small>{desc}</small></div></div>)}<button onClick={()=>setPage('settings')}>연결 설정 열기 <ArrowRight size={16}/></button></section></div><section className="panel"><div className="section-heading"><h2>운영 계정</h2><button className="text-button" onClick={()=>openAccount()}><Plus size={16}/>계정 추가</button></div><div className="account-strip">{data.accounts.length?data.accounts.map((a:Data)=><button key={a.id} className="account-mini" onClick={()=>openAccount(a)}><span className="avatar">{a.name[0]}</span><span><strong>{a.name}</strong><small>{a.paused?'중지':a.auto?'자동 운영':'검토 후 발행'} · {a.live?'실제':'모의'}</small></span><ArrowUpRight size={16}/></button>):<p className="muted">아직 등록된 계정이 없습니다.</p>}</div></section></>}
 {page==='posts'&&<><div className="toolbar"><span>{posts.length}개 콘텐츠</span><button onClick={()=>setModal({type:'import',accountId:filter||data.accounts[0]?.id||'',date:dateTomorrow(),format:'text',content:''})}><Plus size={16}/>작성한 글 일괄 등록</button></div><div className="post-grid">{posts.map(card)}</div>{!posts.length&&<div className="empty">생성하거나 등록한 글이 여기에 표시됩니다.</div>}</>}
 {page==='calendar'&&<section className="panel"><div className="section-heading"><h2>예약 시간순</h2><small>기존 슬롯은 중복 생성하지 않습니다.</small></div>{posts.map((p:Data)=><div className="schedule-row" key={p.id}><div className="schedule-time">{p.date}<small>{new Date(p.scheduledAt).toLocaleTimeString('ko-KR')}</small></div><div><strong>{p.body?.slice(0,55)||'생성 보류'}</strong><small>{accountName(p.accountId)} · 슬롯 {p.slot+1}</small></div><span className={'badge '+p.status}>{labels[p.status]}</span><button onClick={()=>{setFilter(p.accountId);setPage('posts');}}>내용 보기</button></div>)}{!posts.length&&<div className="empty">예약된 콘텐츠가 없습니다.</div>}</section>}
 {page==='accounts'&&<><div className="toolbar"><span>{data.accounts.length}개 운영 계정</span><button className="primary" onClick={()=>openAccount()}><Plus size={16}/>계정 추가</button></div><div className="post-grid">{data.accounts.map((a:Data)=><section className="panel" key={a.id}><div className="row"><span className="avatar">{a.name[0]}</span><h2>{a.name}</h2><span className="badge">{a.live?'실제 발행':'모의 운영'}</span></div><p>{a.theme}</p><p className="muted">{a.tone}</p><dl><dt>게시 시간</dt><dd>{a.times.join(' · ')}</dd><dt>글 구성</dt><dd>일상 {a.everydayRatio} : 제휴 {a.affiliateRatio}</dd><dt>연결</dt><dd>{a.connected?'@'+a.username:'연결하지 않음'}</dd><dt>토큰 만료</dt><dd>{a.expiresAt?new Date(a.expiresAt).toLocaleDateString('ko-KR'):'—'}</dd></dl><div className="actions"><button onClick={()=>openAccount(a)}>설정 변경</button><button onClick={()=>run(async()=>{const r=await api('oauth/start',{accountId:a.id});window.location.href=r.url;},'')}>Threads 연결</button>{a.connected&&<><button onClick={()=>run(()=>api(`accounts/${a.id}/refresh`,{}))}>토큰 갱신</button><button onClick={()=>run(()=>api(`accounts/${a.id}/disconnect`,{}))}>연결 해제</button></>}</div></section>)}</div></>}
 {page==='topics'&&<><div className="toolbar"><span>계정 추가 시 기본 주제 20개가 등록됩니다.</span><button className="primary" onClick={()=>setModal({type:'topic',accountId:filter||data.accounts[0]?.id||'',title:'',source:'',evidence:'',verified:false,expiresAt:'',active:true,priority:1})}><Plus size={16}/>주제 추가</button></div><section className="panel"><div className="topic-grid">{data.topics.filter((t:Data)=>!filter||t.accountId===filter).map((t:Data)=><button key={t.id} className="topic-card" onClick={()=>setModal({...t,type:'topic'})}><Lightbulb size={19}/><strong>{t.title}</strong><small>{accountName(t.accountId)} · {t.uses}회 사용</small><span className="badge">{t.verified?'근거 확인':'일반 관찰 소재'}</span></button>)}</div></section></>}
 {page==='products'&&<><div className="toolbar"><span>정확한 링크와 확인된 정보만 사용합니다.</span><button className="primary" onClick={()=>openProduct()}><Plus size={16}/>상품 등록</button></div><div className="post-grid">{data.products.filter((p:Data)=>!filter||p.accountId===filter).map((p:Data)=><section className="panel" key={p.id}><div className="row"><Package size={23}/><h2>{p.name}</h2><span className="badge">{p.verified?'근거 확인':'확인 필요'}</span></div><p>{p.features}</p><small>{accountName(p.accountId)} · {p.program} · {p.validUntil}까지 유효</small><p className="disclosure">{p.prefix} {p.disclosure}</p><button onClick={()=>openProduct(p)}>상품 · 링크 수정</button></section>)}</div></>}
 {page==='logs'&&<section className="panel"><div className="section-heading"><h2>최근 운영 기록</h2><small>최근 200건</small></div><div className="table-wrap"><table><thead><tr><th>시간</th><th>계정</th><th>종류</th><th>내용</th></tr></thead><tbody>{data.logs.map((l:Data)=><tr key={l.id}><td>{new Date(l.at).toLocaleString('ko-KR')}</td><td>{l.account?accountName(l.account):'전체'}</td><td>{l.event}</td><td>{l.detail}</td></tr>)}</tbody></table></div></section>}
 {page==='settings'&&<div className="settings-grid"><section className="panel"><div className="row"><Sparkles size={23}/><h2>글 생성 연결</h2></div><div className="provider"><div><strong>Gemini</strong><span className="badge">기본 생성기</span><small>{data.settings.geminiModel||'모델 선택 필요'} · {data.settings.hasGemini?'키 저장됨':'키 미설정'}</small></div><ShieldCheck size={23}/></div><div className="provider"><div><strong>GPT · ChatGPT 구독</strong><span className="badge">장애 시 대체</span><small>{data.settings.openaiModel||'Codex 기본 모델'} · {data.settings.fallback?'대체 사용 켜짐':'대체 사용 꺼짐'}</small></div></div><p className="muted">GPT는 이 PC의 Codex ChatGPT 로그인을 사용합니다. OpenAI API 키 과금 경로는 사용하지 않습니다.</p><button className="primary" onClick={()=>setModal({...data.settings,type:'settings',geminiKey:'',openaiKey:'',appSecret:''})}>연결 · 모델 · 예산 설정</button><div className="actions">{(['gemini','openai'] as const).map(p=><button key={p} disabled={busy} onClick={()=>run(async()=>{const r=await api('model-test',{provider:p});setNotice(r.message);},'')}>{p==='gemini'?'Gemini':'GPT'} 연결 시험</button>)}</div></section><section className="panel"><h2>사용량과 운영 상태</h2><dl><dt>오늘 생성 요청</dt><dd>{data.usage.filter((u:Data)=>u.day===new Date().toISOString().slice(0,10)).length} / {data.settings.dailyCalls}회</dd><dt>기존 API 예약 기록</dt><dd>${data.usage.filter((u:Data)=>u.day.startsWith(new Date().toISOString().slice(0,7))).reduce((n:number,u:Data)=>n+u.reservedUsd,0).toFixed(2)} / ${data.settings.monthlyUsd}</dd><dt>실제 발행 허용</dt><dd>{data.liveEnabled?'환경 설정에서 허용':'환경 설정에서 꺼짐'}</dd><dt>Threads 앱</dt><dd>{data.settings.appId||'미설정'}</dd><dt>조회 · 클릭 · 주문 · 수익</dt><dd>수집 불가</dd></dl><div className="warning">GPT는 ChatGPT 구독의 Codex 사용 한도가 적용됩니다. 로그인 만료나 한도 초과 시 보류하며 API로 전환하지 않습니다. Gemini 요금은 연결한 프로젝트 설정에 따릅니다.</div></section></div>}
 <footer>Threads Studio <span>로컬 작업실 · 화면을 닫아도 서버가 켜져 있으면 예약을 처리합니다.</span></footer></div></main>
 {modal&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="설정 편집"><div className="section-heading"><h2>{{account:'운영 계정 설정',product:'상품 · 제휴 정보',topic:'주제 설정',plan:'글 생성 · 예약 준비',import:'작성한 글 일괄 등록',edit:'콘텐츠 수정',settings:'연결 · 모델 · 예산 설정'}[modal.type as string]}</h2><button aria-label="닫기" onClick={()=>setModal(null)}>×</button></div><form onSubmit={submit}><div className="form-fields">
 {modal.type==='account'&&<>{field('운영 이름','name','text',{required:true})}{field('주제 · 카테고리','theme','textarea')}{field('대상 독자','audience')}{field('말투와 글쓰기 규칙','tone','textarea')}{field('확인된 사실 · 실제 경험','facts','textarea')}{field('금지 표현 (쉼표 구분)','banned')}{field('게시 시각 3개 (쉼표 구분)','timesText')}{field('시간대','timezone')}{field('일상글 비율','everydayRatio','number',{min:1})}{field('제휴글 비율','affiliateRatio','number',{min:0})}{field('초기 일상글 전용 기간 (일)','warmupDays','number',{min:0})}{field('상품 재소개 간격 (일)','productInterval','number',{min:1})}{field('계정별 하루 AI 호출 한도','dailyCalls','number',{min:0})}{field('게시 지연 허용 (분)','graceMinutes','number',{min:1,max:120})}{field('상품 부족 시 일상글로 대체','fallbackEveryday','checkbox')}{field('검증 통과 글 자동 승인 · 다음 날 자동 생성','auto','checkbox')}{field('계정 운영 중지','paused','checkbox')}{field('실제 발행 (Threads 연결 및 환경 허용 필요)','live','checkbox')}<p className="hint">새 계정은 검토 모드로 시작합니다. 자동 운영을 켜기 전에 시험 글과 연결을 확인하세요.</p></>}
 {modal.type==='topic'&&<>{selectAccount()}{field('주제명','title','text',{required:true})}{field('출처 URL','source')}{field('확인한 사실 · 경험 원문','evidence','textarea')}{field('근거를 직접 확인함','verified','checkbox')}{field('유효기간 (선택)','expiresAt','date')}{field('우선순위 (1–10)','priority','number',{min:1,max:10})}{field('사용 중','active','checkbox')}</>}
 {modal.type==='product'&&<>{selectAccount()}{field('상품명 · 옵션','name','text',{required:true})}{field('제휴 프로그램','program','text',{required:true})}{field('발급받은 정확한 제휴 URL','url','url',{required:true})}{field('원본 상품 · 근거 URL','source','url',{required:true})}{field('확인된 특징 · 장점 · 한계','features','textarea',{required:true})}{field('본문 첫 광고 문구','prefix')}{field('답글 경제적 이해관계 문구','disclosure','textarea',{required:true})}{field('제휴사 광고 표시 정책 URL','policyUrl','url',{required:true})}{field('정보 확인일','verifiedAt','date',{required:true})}{field('정보 유효기간','validUntil','date',{required:true})}{field('상품 근거·링크·고지 조건을 확인함','verified','checkbox')}{field('판매 · 사용 가능','active','checkbox')}<label className="field">미디어 종류<select value={modal.mediaType} onChange={e=>setModal({...modal,mediaType:e.target.value})}><option>TEXT</option><option>IMAGE</option><option>VIDEO</option></select></label>{field('공개 HTTPS 미디어 주소 (이미지·영상)','mediaUrl')}{field('미디어 출처 · 사용 권한','mediaRights','textarea')}{field('대체 텍스트','alt')}</>}
 {modal.type==='plan'&&<>{selectAccount()}{field('시작 날짜','date','date',{required:true})}{field('준비할 날짜 수 (3일 = 9개)','days','number',{min:1,max:3})}<p className="hint">등록된 주제와 검증된 상품에서 소재를 선택합니다. 계정의 자동 승인 설정이 꺼져 있으면 검토 대기로 저장합니다. 이미 사용한 슬롯은 건너뜁니다.</p></>}
 {modal.type==='import'&&<>{selectAccount()}{field('첫 예약 날짜','date','date',{required:true})}<label className="field">입력 형식<select value={modal.format} onChange={e=>setModal({...modal,format:e.target.value})}><option value="text">일상글 텍스트 (---로 구분)</option><option value="json">JSON (본문 · 답글 · 상품)</option></select></label>{field('글 내용','content','textarea',{required:true,rows:12,placeholder:modal.format==='json'?'[{"body":"본문", "replies":["답글"], "productId":"상품 ID (선택)"}]':'첫 번째 글\n---\n두 번째 글'})}<p className="hint">등록한 글은 검토 후 승인해야 예약됩니다. 상품 ID가 있는 글은 등록된 고지와 링크를 적용합니다.</p></>}
 {modal.type==='edit'&&<>{field('본문','body','textarea',{rows:8,maxLength:500})}{field('자기 답글 (여러 개는 줄 사이 ---로 구분)','replyText','textarea',{rows:8})}<p className="hint">수정하면 기존 승인이 해제되고 다시 검증합니다.</p></>}
 {modal.type==='settings'&&<>{field('Gemini API 키 (빈칸이면 기존 값 유지)','geminiKey','password',{autoComplete:'new-password'})}{field('Gemini 모델 ID','geminiModel')}{field('Codex 구독 모델 ID (빈칸: 기본 모델)','openaiModel')}<div className="actions">{['gemini','openai'].map(p=><button type="button" key={p} onClick={()=>run(async()=>{await api('settings',modal);setModelList(await api('models',{provider:p}));},'모델 목록을 불러왔습니다.')}>{p} 모델 목록 조회</button>)}</div>{modelList.length>0&&<p className="model-list">{modelList.join(' · ')}</p>}{field('Gemini 장애 시 GPT 대체 사용','fallback','checkbox')}{field('전체 하루 생성 요청 한도','dailyCalls','number',{min:0})}{field('Threads 앱 ID','appId')}{field('Threads 앱 시크릿 (빈칸이면 유지)','appSecret','password',{autoComplete:'new-password'})}<p className="hint">OAuth 리디렉션 주소: {window.location.origin}/oauth/callback<br/>키를 저장한 뒤 연결 시험을 실행하세요. GPT는 터미널의 codex login으로 ChatGPT 로그인하세요.</p></>}
 </div><div className="modal-footer"><button type="button" onClick={()=>setModal(null)}>닫기</button><button className="primary" disabled={busy} type="submit">{busy?'처리 중…':modal.type==='plan'?'글 생성 시작':'저장'}</button></div></form></section></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
