import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,CalendarDays,FileText,Package,Lightbulb,Settings,Activity,Plus,ArrowUpRight,Pause,Play,Check,ArrowRight,LogOut,Sparkles,ShieldCheck,Trash2,ChevronDown,List,LayoutGrid} from 'lucide-react';
import './style.css';
type Data=Record<string,any>;
let activeProfile='';
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-Profile-Id':activeProfile},body:body===undefined?undefined:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error||'요청에 실패했습니다.');return value;}
const labels:Data={review:'검토 대기',blocked:'검증 실패',scheduled:'예약 완료',publishing:'발행 중',partial:'답글 미완료',complete:'전체 완료',uncertain:'결과 확인 필요',held:'보류',cancelled:'취소',skipped:'건너뜀'};
const nav=[['dashboard','대시보드',LayoutDashboard],['posts','콘텐츠 검토',FileText],['calendar','예약 일정',CalendarDays],['accounts','계정 관리',Users],['topics','주제 보관함',Lightbulb],['products','상품 · 제휴 링크',Package],['logs','발행 기록',Activity],['settings','연결 및 설정',Settings]] as const;
const categoryOptions=['일상 · 라이프','정리 · 수납','생산성 · 습관','직장 · 커리어','자영업 · 사업','마케팅 · 브랜딩','IT · 디지털','AI · 자동화','재테크 · 경제','건강 · 운동','뷰티 · 패션','요리 · 식품','여행 · 지역','육아 · 가족','취미 · 문화'];
const styleNames:Data={dialogue:'대화 속 발견',scene:'생활 장면',reversal:'작은 반전',contrast:'두 가지 비교',note:'짧은 메모',observation:'공감 관찰',steps:'작은 실천',question:'질문에서 시작'};
const audienceOptions=['일상을 편하게 만들고 싶은 사람','바쁜 직장인','자영업자와 소상공인','콘텐츠를 만드는 사람','AI와 자동화를 처음 쓰는 사람','디지털 생산성을 높이고 싶은 사람','재테크를 처음 시작하는 사람','건강한 습관을 만들고 싶은 사람','육아와 가족 생활에 관심 있는 사람','새로운 취미와 트렌드를 찾는 사람'];
const fixedTone='친구에게 말하듯 편한 반말. 생활정보를 대화·장면·반전 등 다양한 이야기로 풀되, 재구성한 장면을 실제 경험의 증거로 삼지 않는다.';
const dateTomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(d);};
const seoulDate=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(d);
const dayLabel=(date:string)=>new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short',timeZone:'UTC'}).format(new Date(date+'T00:00:00Z'));
const timeLabel=(iso:string)=>new Date(iso).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Seoul'});
// server/domain.ts의 canDeletePost와 같은 규칙입니다. 버튼 표시용이며 최종 판단은 서버가 합니다.
const canDelete=(p:Data)=>['review','blocked','held','cancelled','skipped'].includes(p.status)&&!p.steps.some((s:Data)=>s.postId||['creating','sending','uncertain'].includes(s.status))&&!(p.status==='held'&&!p.body&&!p.error);
const statusGroups:Record<string,[string,string[]|null]>={active:['진행 중',['review','blocked','scheduled','publishing','partial','uncertain','held']],review:['검토 대기',['review','blocked']],complete:['완료',['complete']],closed:['취소 · 건너뜀',['cancelled','skipped']],all:['전체',null]};
function App(){
 const [loginProfile,setLoginProfile]=useState('GEOM');
 const [session,setSession]=useState<Data|null>(null),[data,setData]=useState<Data|null>(null),[page,setPage]=useState('dashboard'),[filter,setFilter]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<Data|null>(null),[connectionResult,setConnectionResult]=useState<Data>({});
 const [view,setView]=useState(()=>{try{return localStorage.getItem('postView')||'list';}catch{return 'list';}}),[statusFilter,setStatusFilter]=useState('active'),[open,setOpen]=useState('');
 const changeView=(v:string)=>{setView(v);try{localStorage.setItem('postView',v);}catch{}};
 const refresh=async()=>{const next=await api('state');if(activeProfile&&activeProfile!==next.profileId){activeProfile='';setData(null);setModal(null);setFilter('');setSession({authenticated:false});setNotice('다른 탭에서 프로필이 변경되었습니다. 사용할 프로필을 다시 선택하세요.');return;}activeProfile=next.profileId;setData(next);};
 useEffect(()=>{api('session').then(async s=>{setSession(s);if(s.authenticated)await refresh();}).catch(e=>setNotice(e.message));},[]);
 useEffect(()=>{if(!session?.authenticated)return;const timer=setInterval(()=>refresh().catch(()=>{}),15000);return()=>clearInterval(timer);},[session?.authenticated]);
 async function run(fn:()=>Promise<any>,message='저장했습니다.'){setBusy(true);setNotice('');try{const out=await fn();await refresh();const text=typeof out==='string'?out:message;if(text)setNotice(text);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 const field=(label:string,key:string,type='text',extra:Data={})=><label className="field">{label}{type==='textarea'?<textarea value={modal?.[key]??''} onChange={e=>setModal({...modal,[key]:e.target.value})} {...extra}/>:type==='checkbox'?<input type="checkbox" checked={!!modal?.[key]} onChange={e=>setModal({...modal,[key]:e.target.checked})}/>:<input type={type} value={modal?.[key]??''} onChange={e=>setModal({...modal,[key]:type==='number'?Number(e.target.value):e.target.value})} {...extra}/>}</label>;
 const choice=(label:string,key:string,options:string[])=><label className="field">{label}<select value={modal?.[key]??options[0]} onChange={e=>setModal({...modal,[key]:e.target.value})}>{modal?.[key]&&!options.includes(modal[key])&&<option value={modal[key]}>현재 값 · {modal[key]}</option>}{options.map(value=><option key={value} value={value}>{value}</option>)}</select></label>;
 const ownAccounts=(data?.accounts||[]).filter((a:Data)=>a.profileId===data?.profileId);
 const selectAccount=()=> <label className="field">운영 계정<select required value={modal?.accountId||''} onChange={e=>setModal({...modal,accountId:e.target.value})}><option value="">계정 선택</option>{ownAccounts.map((a:Data)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>;
 const accountName=(id:string)=>data?.accounts.find((a:Data)=>a.id===id)?.name||'계정';
 const openAccount=(a:Data={})=>setModal({type:'account',name:'',theme:categoryOptions[0],audience:audienceOptions[0],facts:'',banned:'무조건,역대급,최저가,품절 임박',timesText:'08:00,12:30,21:30',timezone:'Asia/Seoul',everydayRatio:2,affiliateRatio:1,warmupDays:0,productInterval:14,dailyCalls:50,graceMinutes:30,auto:false,paused:false,live:false,fallbackEveryday:true,...a,tone:fixedTone,...(a.times?{timesText:a.times.join(',')}:{})});
 // 내일부터 슬롯 3개가 모두 찬 날짜는 건너뛰고 첫 빈 날짜를 기본값으로 제안합니다.
 const nextFreeDate=(accountId:string)=>{for(let i=1;i<=60;i++){const day=seoulDate(new Date(Date.now()+i*86400000));if((data?.posts||[]).filter((p:Data)=>p.accountId===accountId&&p.date===day).length<3)return day;}return dateTomorrow();};
 const openPlan=()=>{const accountId=filter||ownAccounts[0]?.id||'';setModal({type:'plan',accountId,date:accountId?nextFreeDate(accountId):dateTomorrow(),days:1});};
 const removePosts=(list:Data[])=>{if(!list.length||!window.confirm(`${list.length}개 글을 삭제할까요? 되돌릴 수 없습니다.`))return;run(async()=>{for(const p of list)await api(`posts/${p.id}/action`,{action:'delete'});if(list.some(p=>p.id===open))setOpen('');},`${list.length}개 글을 삭제했습니다.`);};
 const openProduct=(p:Data={})=>setModal({type:'product',accountId:filter||ownAccounts[0]?.id||'',name:'',program:'',url:'',source:'',features:'',disclosure:'',prefix:'[광고]',policyUrl:'',verified:false,verifiedAt:new Date().toISOString().slice(0,10),validUntil:dateTomorrow(),active:true,mediaType:'TEXT',mediaUrl:'',mediaRights:'',alt:'',...p});
 async function submit(e:React.FormEvent){e.preventDefault();if(!modal)return;await run(async()=>{const m=modal;let done='';if(m.type==='account')await api('accounts',{...m,tone:fixedTone,times:m.timesText.split(',').map((x:string)=>x.trim())});if(m.type==='product')await api('products',m);if(m.type==='topic')await api('topics',m);if(m.type==='plan'){const r=await api('plan',m);if(!r.length)throw Error('선택한 날짜는 이미 글 3개가 모두 차 있습니다. 기존 글을 삭제하거나 다른 날짜를 고르세요.');const failed=r.filter((x:Data)=>x.error);setPage('posts');setStatusFilter('active');setOpen('');done=failed.length?`${r.length-failed.length}개 생성, ${failed.length}개 실패: ${failed[0].error}`:`${r.length}개 글을 만들었습니다. 검토 후 승인하세요.`;}
 if(m.type==='import'){let items;if(m.format==='json')items=JSON.parse(m.content);else items=m.content.split(/\n\s*---\s*\n/).filter((x:string)=>x.trim()).map((body:string)=>({body:body.trim(),replies:[]}));const r=await api('import',{...m,items});if(!r.count)throw Error('선택한 날짜의 예약 슬롯이 이미 사용 중입니다.');setPage('posts');setStatusFilter('active');done=`${r.count}개 글을 등록했습니다.`;}
 if(m.type==='rewrite'){await api(`posts/${m.id}/rewrite`,{feedback:m.feedback||''});done='다른 구성으로 다시 썼습니다. 내용을 확인하고 승인해 주세요.';}
 if(m.type==='edit')await api(`posts/${m.id}/action`,{action:'edit',body:m.body,replies:m.replyText?m.replyText.split('\n---\n'):[]});
 if(m.type==='pin'){if(m.newPin!==m.confirmPin)throw Error('새 PIN 확인이 일치하지 않습니다.');await api('profile/pin',m);}
 if(m.type==='settings')await api('settings',m);setModal(null);return done||undefined;});}
 if(!session)return <div className="loading">Threads Studio를 열고 있습니다…{notice}</div>;
 if(!session.authenticated)return <div className="login"><div className="login-art"><div className="wordmark">◉ THREADS STUDIO</div><h1>함께 만드는 이야기,<br/>게시 계정은 각자의 것으로.</h1><p>프로필을 선택해 작업실에 들어오세요.<br/>자료와 설정은 함께 사용합니다.</p><span className="login-note">GEOM & KYU · SHARED WORKSPACE</span></div><form className="login-form" onSubmit={async e=>{e.preventDefault();const pin=new FormData(e.currentTarget).get('pin');setBusy(true);try{const r=await api('login',{profileId:loginProfile,pin});activeProfile=r.profileId;setSession({authenticated:true,profileId:r.profileId});setFilter('');setModal(null);setNotice('');await refresh();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}><div className="eyebrow">CHOOSE YOUR PROFILE</div><h2>누구의 계정으로 게시할까요?</h2><div className="profile-picker">{['GEOM','KYU'].map(name=><button key={name} type="button" aria-pressed={loginProfile===name} className={loginProfile===name?'selected':''} onClick={()=>{setLoginProfile(name);setNotice('');}}><span className="avatar">{name[0]}</span>{name}</button>)}</div><label className="field">{loginProfile} PIN<input key={loginProfile} name="pin" type="password" inputMode="numeric" pattern="[0-9]{4}" minLength={4} maxLength={4} required autoComplete="current-password" placeholder="숫자 4자리"/></label><button className="primary" disabled={busy}>{loginProfile} 작업실 열기 <ArrowRight size={17}/></button>{notice&&<p role="alert" className="notice">{notice}</p>}<small>개발용 초기 PIN은 0000입니다.<br/>로그인 후 ‘PIN 변경’에서 바꿀 수 있습니다.</small></form></div>;
 if(!data)return <div className="loading">운영 정보를 불러오고 있습니다…</div>;
 const posts=data.posts.filter((p:Data)=>!filter||p.accountId===filter).sort((a:Data,b:Data)=>a.scheduledAt.localeCompare(b.scheduledAt));
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());const todayPosts=posts.filter((p:Data)=>p.date===today);const issues=posts.filter((p:Data)=>['blocked','held','uncertain','partial'].includes(p.status));
 const canManage=(p:Data)=>ownAccounts.some((a:Data)=>a.id===p.accountId);
 const card=(p:Data)=><article className="post-card" key={p.id}><div className="row"><span className="avatar">{accountName(p.accountId).slice(0,1)}</span><div><strong>{accountName(p.accountId)}</strong><small>{p.date} · {new Date(p.scheduledAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</small></div><span className={'badge '+p.status}>{labels[p.status]}</span></div><div className="post-body">{p.body||'글 생성이 보류되었습니다.'}</div>{p.replies.map((r:string,i:number)=><div className="reply" key={i}><small>↳ 자기 답글 {i+1}</small><p>{r}</p></div>)}{p.product?.mediaUrl&&<a href={p.product.mediaUrl} target="_blank" rel="noreferrer" className="link">등록 미디어 확인 ↗</a>}{(p.error||p.issues?.length>0)&&<div className="warning">{p.error||p.issues.join(' / ')}</div>}<div className="post-meta"><span>{p.kind==='affiliate'?'제휴 콘텐츠':'일상 콘텐츠'} · {p.simulated?'모의 발행':'실제 발행'}</span><span>v{p.version} · {p.provider}{p.writingStyle?' · '+(styleNames[p.writingStyle]||p.writingStyle):''}</span></div><details><summary>근거와 단계별 결과</summary><p>{p.evidence.join('\n')||'등록 근거 없음 · 일반 관찰형 글만 허용'}</p>{p.brief&&<p>{Object.values(p.brief).join(' · ')}</p>}{p.steps.map((s:Data,i:number)=><p key={s.key}>{i===0?'본문':'답글 '+i}: {s.postId||s.status} {s.permalink&&<a href={s.permalink} target="_blank" rel="noreferrer">게시물 보기 ↗</a>}</p>)}</details><div className="actions">{canManage(p)&&['review','blocked','held'].includes(p.status)&&(p.body||p.error)&&!p.steps.some((s:Data)=>s.postId||s.containerId||['sending','creating','uncertain'].includes(s.status))&&<button disabled={busy||(p.rewriteCount||0)>=5} onClick={()=>setModal({...p,type:'rewrite',feedback:''})}><Sparkles size={14}/>AI 다시쓰기 ({p.rewriteCount||0}/5)</button>}{!canManage(p)&&<small>다른 프로필의 게시 계정 · 조회만 가능</small>}{canManage(p)&&['review','blocked'].includes(p.status)&&<><button className="primary small" disabled={busy} onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'approve'}),'검증 후 예약했습니다.')}><Check size={15}/>승인 · 예약</button><button onClick={()=>setModal({...p,type:'edit',replyText:p.replies.join('\n---\n')})}>수정</button></>}{canManage(p)&&['held','partial'].includes(p.status)&&p.approvedHash&&<button onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'retry'}))}>남은 단계 재시도</button>}{canManage(p)&&p.status==='uncertain'&&<button onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'reconcile'}),'결과 확인 상태를 갱신했습니다.')}>게시 결과 확인</button>}{canManage(p)&&!['complete','cancelled','publishing','uncertain'].includes(p.status)&&<button onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'hold'}))}>보류</button>}{canManage(p)&&!['complete','cancelled','publishing','uncertain'].includes(p.status)&&<button className="text-button" onClick={()=>run(()=>api(`posts/${p.id}/action`,{action:'cancel'}))}>취소</button>}{canManage(p)&&canDelete(p)&&<button className="text-button danger" disabled={busy} onClick={()=>removePosts([p])}><Trash2 size={14}/>삭제</button>}</div></article>;
 return <div className="shell"><aside><button className="brand" type="button" aria-label="대시보드로 이동" onClick={()=>setPage('dashboard')}><img src="/g-threads-logo.png" alt=""/><span className="brand-name"><span className="brand-line">{'Threads'.split('').map((c,i)=><span key={i}>{c}</span>)}</span><span className="brand-line brand-studio">{'STUDIO'.split('').map((c,i)=><span key={i}>{c}</span>)}</span></span></button><div className="workspace-label">WORKSPACE</div><nav>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}><Icon size={19}/>{label}{key==='posts'&&<b>{data.posts.filter((p:Data)=>p.status==='review').length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="engine-label"><Sparkles size={17}/><span>Gemini 우선 생성<small>{data.settings.fallback?'GPT 대체 경로 활성':'GPT 대체 경로 미설정'}</small></span></div><button className="logout" onClick={async()=>{await api('logout',{});activeProfile='';setData(null);setFilter('');setModal(null);setSession({authenticated:false});}}><LogOut size={16}/>프로필 전환</button></div></aside><main><header><div className="breadcrumb">작업실 <span>/</span> {nav.find(x=>x[0]===page)?.[1]}</div><div className="header-right"><strong className="profile-label">{data.profileId}</strong><button onClick={()=>setModal({type:'pin',currentPin:'',newPin:'',confirmPin:''})}>PIN 변경</button><span className="mode-label">{data.settings.stopped?'발행 중지됨':'예약 처리 중'}</span><button className={data.settings.stopped?'resume':'stop'} disabled={busy} onClick={()=>run(()=>api('stop',{stopped:!data.settings.stopped}),data.settings.stopped?'운영을 재개했습니다.':'신규 발행을 중지했습니다.')} >{data.settings.stopped?<Play size={15}/>:<Pause size={15}/>} {data.settings.stopped?'운영 재개':'전체 중지'}</button></div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">{page==='dashboard'?'CONTENT, ON YOUR TERMS.':'THREADS STUDIO'}</div><h1>{page==='dashboard'?'오늘의 작업실':nav.find(x=>x[0]===page)?.[1]}</h1><p>{page==='dashboard'?'계정의 하루를 살펴보고, 다음 이야기를 준비하세요.':page==='posts'?'본문과 답글, 사용한 근거를 함께 확인하세요.':page==='settings'?'두 프로필이 공유하는 AI 연결과 자동 모델 선택을 확인하세요.':'계정별 운영 정보를 관리하세요.'}</p></div><div className="heading-actions"><select aria-label="계정 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">모든 계정</option>{data.accounts.map((a:Data)=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{['dashboard','posts','calendar'].includes(page)&&<button className="primary" onClick={openPlan}><Sparkles size={16}/>글 생성 · 예약 준비</button>}</div></div>{notice&&<div role="status" className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}{busy&&<div className="busy" role="status">처리 중입니다. 생성은 잠시 걸릴 수 있습니다…</div>}
 {page==='dashboard'&&<><div className="metrics">{[['오늘 예정',todayPosts.length,'하루 본문 기준'],['본문 게시',todayPosts.filter((p:Data)=>p.steps[0]?.postId).length,'모의 / 실제 표시는 글별 확인'],['전체 완료',todayPosts.filter((p:Data)=>p.status==='complete').length,'답글까지 처리 완료'],['확인할 항목',issues.length,'검증 · 연결 · 생성 문제']].map(([label,n,sub],i)=><section className={'metric m'+i} key={label}><span>{label}</span><strong>{String(n).padStart(2,'0')}<small>건</small></strong><p>{sub}</p></section>)}</div><div className="dashboard-grid"><section className="panel"><div className="section-heading"><h2>다음 발행 일정</h2><button className="text-button" onClick={()=>setPage('calendar')}>전체 일정 <ArrowUpRight size={16}/></button></div>{posts.filter((p:Data)=>!['complete','cancelled','skipped'].includes(p.status)).slice(0,5).map((p:Data)=><div className="schedule-row" key={p.id}><div className="schedule-time">{new Date(p.scheduledAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false})}<small>{p.date.slice(5)}</small></div><div><strong>{p.body?.slice(0,42)||'생성 대기 · '+accountName(p.accountId)}</strong><small>{accountName(p.accountId)} · {p.kind==='affiliate'?'제휴':'일상'} · {p.simulated?'모의':'실제'}</small></div><span className={'badge '+p.status}>{labels[p.status]}</span></div>)}{!posts.length&&<div className="empty"><CalendarDays size={32}/><h3>첫 번째 이야기를 준비해 볼까요?</h3><p>계정을 추가하고 주제를 정하면<br/>다음 날의 글을 미리 준비할 수 있어요.</p><button onClick={()=>openAccount()}><Plus size={16}/>계정 추가</button></div>}</section><section className="setup-panel"><span className="eyebrow">READY WHEN YOU ARE</span><h2>자동화 준비</h2>{[[data.accounts.length>0,'운영 계정 등록','주제 · 말투 · 게시 시간'],[data.settings.hasGemini,'Gemini 연결','API 키 저장 · 모델 시험'],[data.accounts.some((a:Data)=>a.connected),'Threads 계정 연결','공식 로그인과 게시 권한'],[data.posts.some((p:Data)=>p.status==='scheduled'),'콘텐츠 검토','근거 확인 후 승인']].map(([ok,title,desc],i)=><div className="setup-step" key={String(title)}><span className={ok?'done':''}>{ok?<Check size={16}/>:i+1}</span><div><strong>{title}</strong><small>{desc}</small></div></div>)}<button onClick={()=>setPage('settings')}>연결 설정 열기 <ArrowRight size={16}/></button></section></div><section className="panel"><div className="section-heading"><h2>운영 계정</h2><button className="text-button" onClick={()=>openAccount()}><Plus size={16}/>계정 추가</button></div><div className="account-strip">{data.accounts.length?data.accounts.map((a:Data)=><button key={a.id} className="account-mini" onClick={()=>a.profileId===data.profileId?openAccount(a):setNotice('다른 프로필의 게시 계정입니다. 프로필을 전환해 주세요.')}><span className="avatar">{a.name[0]}</span><span><strong>{a.name}</strong><small>{a.paused?'중지':a.auto?'자동 운영':'검토 후 발행'} · {a.live?'실제':'모의'}</small></span><ArrowUpRight size={16}/></button>):<p className="muted">아직 등록된 계정이 없습니다.</p>}</div></section></>}
 {page==='posts'&&(()=>{
  const statuses=statusGroups[statusFilter]?.[1];
  // 진행 중·검토 대기는 가까운 예약부터, 완료·취소·전체는 최근 글부터 보여 줍니다.
  const shown=posts.filter((p:Data)=>!statuses||statuses.includes(p.status));const ordered=['active','review'].includes(statusFilter)?shown:[...shown].reverse();
  const cleanup=posts.filter((p:Data)=>canManage(p)&&canDelete(p)&&['cancelled','skipped','held'].includes(p.status));
  return <><div className="toolbar"><span>{shown.length}개 콘텐츠</span><div className="toolbar-actions"><div className="segmented" role="group" aria-label="보기 방식"><button aria-pressed={view==='list'} className={view==='list'?'active':''} onClick={()=>changeView('list')}><List size={15}/>목록</button><button aria-pressed={view==='cards'} className={view==='cards'?'active':''} onClick={()=>changeView('cards')}><LayoutGrid size={15}/>카드</button></div>{cleanup.length>0&&<button disabled={busy} onClick={()=>removePosts(cleanup)}><Trash2 size={15}/>취소 · 실패 글 정리 ({cleanup.length})</button>}<button onClick={()=>setModal({type:'import',accountId:filter||ownAccounts[0]?.id||'',date:dateTomorrow(),format:'text',content:''})}><Plus size={16}/>작성한 글 일괄 등록</button></div></div>
  <div className="status-tabs" role="tablist">{Object.entries(statusGroups).map(([key,[label,list]])=><button key={key} role="tab" aria-selected={statusFilter===key} className={statusFilter===key?'active':''} onClick={()=>{setStatusFilter(key);setOpen('');}}>{label}<b>{posts.filter((p:Data)=>!list||list.includes(p.status)).length}</b></button>)}</div>
  {view==='cards'?<div className="post-grid">{ordered.map(card)}</div>:ordered.length>0&&<div className="post-list">{ordered.map((p:Data,i:number)=><React.Fragment key={p.id}>{(i===0||ordered[i-1].date!==p.date)&&<div className="list-date">{dayLabel(p.date)}</div>}<div className={'post-row'+(open===p.id?' open':'')}><button className="row-main" aria-expanded={open===p.id} onClick={()=>setOpen(open===p.id?'':p.id)}><span className="row-time">{timeLabel(p.scheduledAt)}</span><span className="row-account">{accountName(p.accountId)}</span><span className={'row-text'+(p.body?'':' muted')}>{p.body?p.body.replace(/\s+/g,' '):p.error?'글 생성 실패 · '+p.error:'글 생성 대기'}</span><span className={'badge '+p.status}>{labels[p.status]}</span><ChevronDown size={16} className="chev"/></button>{canManage(p)&&canDelete(p)&&<button className="icon-button" title="삭제" aria-label="삭제" disabled={busy} onClick={()=>removePosts([p])}><Trash2 size={15}/></button>}</div>{open===p.id&&<div className="row-detail">{card(p)}</div>}</React.Fragment>)}</div>}
  {!shown.length&&<div className="empty">{posts.length?'이 상태의 글이 없습니다.':'생성하거나 등록한 글이 여기에 표시됩니다.'}</div>}</>;})()}
 {page==='calendar'&&<section className="panel"><div className="section-heading"><h2>예약 시간순</h2><small>기존 슬롯은 중복 생성하지 않습니다.</small></div>{posts.map((p:Data)=><div className="schedule-row" key={p.id}><div className="schedule-time">{p.date}<small>{new Date(p.scheduledAt).toLocaleTimeString('ko-KR')}</small></div><div><strong>{p.body?.slice(0,55)||'생성 보류'}</strong><small>{accountName(p.accountId)} · 슬롯 {p.slot+1}</small></div><span className={'badge '+p.status}>{labels[p.status]}</span><button onClick={()=>{setFilter(p.accountId);setPage('posts');}}>내용 보기</button></div>)}{!posts.length&&<div className="empty">예약된 콘텐츠가 없습니다.</div>}</section>}
 {page==='accounts'&&<><div className="toolbar"><span>{data.accounts.length}개 운영 계정</span><button className="primary" onClick={()=>openAccount()}><Plus size={16}/>계정 추가</button></div><div className="post-grid">{ownAccounts.map((a:Data)=><section className="panel" key={a.id}><div className="row"><span className="avatar">{a.name[0]}</span><h2>{a.name}</h2><span className="badge">{a.live?'실제 발행':'모의 운영'}</span></div><p>{a.theme}</p><p className="muted">{a.tone}</p><dl><dt>게시 시간</dt><dd>{a.times.join(' · ')}</dd><dt>글 구성</dt><dd>일상 {a.everydayRatio} : 제휴 {a.affiliateRatio}</dd><dt>연결</dt><dd>{a.connected?'@'+a.username:'연결하지 않음'}</dd><dt>토큰 만료</dt><dd>{a.expiresAt?new Date(a.expiresAt).toLocaleDateString('ko-KR'):'—'}</dd></dl><div className="actions"><button onClick={()=>openAccount(a)}>설정 변경</button><button onClick={()=>run(async()=>{const r=await api('oauth/start',{accountId:a.id});window.location.href=r.url;},'')}>Threads 연결</button>{a.connected&&<><button onClick={()=>run(()=>api(`accounts/${a.id}/refresh`,{}))}>토큰 갱신</button><button onClick={()=>run(()=>api(`accounts/${a.id}/disconnect`,{}))}>연결 해제</button></>}</div></section>)}</div></>}
 {page==='topics'&&<><div className="toolbar"><span>계정 추가 시 기본 주제 20개가 등록됩니다.</span><button className="primary" onClick={()=>setModal({type:'topic',accountId:filter||ownAccounts[0]?.id||'',title:'',source:'',evidence:'',verified:false,expiresAt:'',active:true,priority:1})}><Plus size={16}/>주제 추가</button></div><section className="panel"><div className="topic-grid">{data.topics.filter((t:Data)=>!filter||t.accountId===filter).map((t:Data)=><button key={t.id} className="topic-card" onClick={()=>setModal({...t,type:'topic'})}><Lightbulb size={19}/><strong>{t.title}</strong><small>{accountName(t.accountId)} · {t.uses}회 사용</small><span className="badge">{t.verified?'근거 확인':'일반 관찰 소재'}</span></button>)}</div></section></>}
 {page==='products'&&<><div className="toolbar"><span>정확한 링크와 확인된 정보만 사용합니다.</span><button className="primary" onClick={()=>openProduct()}><Plus size={16}/>상품 등록</button></div><div className="post-grid">{data.products.filter((p:Data)=>!filter||p.accountId===filter).map((p:Data)=><section className="panel" key={p.id}><div className="row"><Package size={23}/><h2>{p.name}</h2><span className="badge">{p.verified?'근거 확인':'확인 필요'}</span></div><p>{p.features}</p><small>{accountName(p.accountId)} · {p.program} · {p.validUntil}까지 유효</small><p className="disclosure">{p.prefix} {p.disclosure}</p><button onClick={()=>openProduct(p)}>상품 · 링크 수정</button></section>)}</div></>}
 {page==='logs'&&<section className="panel"><div className="section-heading"><h2>최근 운영 기록</h2><small>최근 200건</small></div><div className="table-wrap"><table><thead><tr><th>시간</th><th>계정</th><th>종류</th><th>내용</th></tr></thead><tbody>{data.logs.map((l:Data)=><tr key={l.id}><td>{new Date(l.at).toLocaleString('ko-KR')}</td><td>{l.account?accountName(l.account):'전체'}</td><td>{l.event}</td><td>{l.detail}</td></tr>)}</tbody></table></div></section>}
 {page==='settings'&&<div className="settings-grid"><section className="panel"><div className="row"><Sparkles size={23}/><h2>글 생성 연결</h2></div><div className="provider"><div><strong>Gemini</strong><span className="badge">기본 생성기</span><small>{'성공한 모델 유지 · 모델 오류 시 대체'} · {data.settings.hasGemini?'키 저장됨':'키 미설정'}</small></div><ShieldCheck size={23}/></div><div className="provider"><div><strong>GPT · ChatGPT 구독</strong><span className="badge">장애 시 대체</span><small>{'자동 선택 · Codex 기본 모델'} · {data.settings.fallback?'대체 사용 켜짐':'대체 사용 꺼짐'}</small></div></div><p className="muted">GEOM · KYU는 Gemini 키 하나와 이 PC의 ChatGPT 구독 로그인 하나를 공유합니다. Gemini 키는 .env의 GEMINI_API_KEY가 우선 적용됩니다.</p><button className="primary" onClick={()=>setModal({...data.settings,type:'settings',geminiKey:'',openaiKey:'',appSecret:''})}>공통 연결 · 예산 설정</button><div className="actions">{(['gemini','openai'] as const).map(p=><button key={p} disabled={busy} onClick={()=>run(async()=>{setConnectionResult((v:Data)=>({...v,[p]:{state:'testing',message:'짧은 시험 응답을 확인하고 있습니다…'}}));try{const r=await api('model-test',{provider:p});const name=p==='gemini'?'Gemini':'GPT';const message=`${name} 연결 성공 · ${r.model==='auto'?'자동 선택 모델':r.model} · 짧은 응답 확인 완료`;setConnectionResult((v:Data)=>({...v,[p]:{state:'success',message}}));return message;}catch(e){setConnectionResult((v:Data)=>({...v,[p]:{state:'error',message:(e as Error).message}}));throw e;}},'')}>{p==='gemini'?'Gemini':'GPT'} 연결 시험</button>)}</div>{(['gemini','openai'] as const).map(p=>connectionResult[p]&&<p key={p} className={'connection-result '+connectionResult[p].state} role="status">{connectionResult[p].state==='success'?'✓ ':connectionResult[p].state==='error'?'오류 · ':'⏳ '}{connectionResult[p].message}</p>)}</section><section className="panel"><h2>사용량과 운영 상태</h2><dl><dt>오늘 생성 요청</dt><dd>{data.usage.filter((u:Data)=>u.day===new Date().toISOString().slice(0,10)).length} / {data.settings.dailyCalls}회</dd>{Object.entries({generate:'최초 생성',rewrite:'AI 다시쓰기',test:'연결 시험',retry:'재시도 · 대체',legacy:'이전 기록 (분류 없음)'}).map(([kind,label])=><React.Fragment key={kind}><dt>{label}</dt><dd>{data.usage.filter((u:Data)=>u.day===new Date().toISOString().slice(0,10)&&(u.kind||'legacy')===kind).length}회</dd></React.Fragment>)}<dt>실제 발행 허용</dt><dd>{data.liveEnabled?'환경 설정에서 허용':'환경 설정에서 꺼짐'}</dd><dt>Threads 앱</dt><dd>{data.settings.appId||'미설정'}</dd><dt>조회 · 클릭 · 주문 · 수익</dt><dd>수집 불가</dd></dl><div className="warning">GPT는 ChatGPT 구독의 Codex 사용 한도가 적용됩니다. 로그인 만료나 한도 초과 시 보류하며 API로 전환하지 않습니다. Gemini 요금은 연결한 프로젝트 설정에 따릅니다.</div></section></div>}
 <footer>Threads Studio <span>로컬 작업실 · 화면을 닫아도 서버가 켜져 있으면 예약을 처리합니다.</span></footer></div></main>
 {modal&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="설정 편집"><div className="section-heading"><h2>{{pin:'내 프로필 PIN 변경',account:'운영 계정 설정',product:'상품 · 제휴 정보',topic:'주제 설정',plan:'글 생성 · 예약 준비',import:'작성한 글 일괄 등록',edit:'콘텐츠 수정',rewrite:'AI 다시쓰기',settings:'연결 · 모델 · 예산 설정'}[modal.type as string]}</h2><button aria-label="닫기" onClick={()=>setModal(null)}>×</button></div><form onSubmit={submit}><div className="form-fields">
 {modal.type==='pin'&&<><p className="hint">{data.profileId}의 PIN만 변경합니다. 다른 프로필과 기존 예약은 유지됩니다.</p>{field('현재 PIN','currentPin','password',{inputMode:'numeric',pattern:'[0-9]{4}',minLength:4,maxLength:4,required:true,autoComplete:'current-password'})}{field('새 PIN','newPin','password',{inputMode:'numeric',pattern:'[0-9]{4}',minLength:4,maxLength:4,required:true,autoComplete:'new-password'})}{field('새 PIN 확인','confirmPin','password',{inputMode:'numeric',pattern:'[0-9]{4}',minLength:4,maxLength:4,required:true,autoComplete:'new-password'})}</>}
 {modal.type==='account'&&<>{field('운영 이름','name','text',{required:true})}{choice('주제 · 카테고리','theme',categoryOptions)}{choice('대상 독자','audience',audienceOptions)}<div className="fixed-rule"><strong>말투와 글쓰기 규칙 · 고정</strong><span>친구에게 말하듯 편한 반말</span></div><div className="fixed-rule"><strong>확인된 사실 표현 방식 · 고정</strong><span>생활정보를 대화·장면·반전 등 8가지 구성으로 작성. 최근 글과 같은 도입·결말은 피하고, 재구성한 장면을 사실의 근거로 삼지 않음</span></div>{field('금지 표현 (쉼표 구분)','banned')}{field('게시 시각 3개 (쉼표 구분)','timesText')}{field('시간대','timezone')}{field('일상글 비율','everydayRatio','number',{min:1})}{field('제휴글 비율','affiliateRatio','number',{min:0})}{field('초기 일상글 전용 기간 (일)','warmupDays','number',{min:0})}{field('상품 재소개 간격 (일)','productInterval','number',{min:1})}{field('계정별 하루 AI 호출 한도','dailyCalls','number',{min:0})}{field('게시 지연 허용 (분)','graceMinutes','number',{min:1,max:120})}{field('상품 부족 시 일상글로 대체','fallbackEveryday','checkbox')}{field('검증 통과 글 자동 승인 · 다음 날 자동 생성','auto','checkbox')}{field('계정 운영 중지','paused','checkbox')}{field('실제 발행 (Threads 연결 및 환경 허용 필요)','live','checkbox')}<p className="hint">새 계정은 검토 모드로 시작합니다. 자동 운영을 켜기 전에 시험 글과 연결을 확인하세요.</p></>}
 {modal.type==='topic'&&<>{selectAccount()}{field('주제명','title','text',{required:true})}{field('출처 URL','source')}{field('확인한 사실 · 경험 원문','evidence','textarea')}{field('근거를 직접 확인함','verified','checkbox')}{field('유효기간 (선택)','expiresAt','date')}{field('우선순위 (1–10)','priority','number',{min:1,max:10})}{field('사용 중','active','checkbox')}</>}
 {modal.type==='product'&&<>{selectAccount()}{field('상품명 · 옵션','name','text',{required:true})}{field('제휴 프로그램','program','text',{required:true})}{field('발급받은 정확한 제휴 URL','url','url',{required:true})}{field('원본 상품 · 근거 URL','source','url',{required:true})}{field('확인된 특징 · 장점 · 한계','features','textarea',{required:true})}{field('본문 첫 광고 문구','prefix')}{field('답글 경제적 이해관계 문구','disclosure','textarea',{required:true})}{field('제휴사 광고 표시 정책 URL','policyUrl','url',{required:true})}{field('정보 확인일','verifiedAt','date',{required:true})}{field('정보 유효기간','validUntil','date',{required:true})}{field('상품 근거·링크·고지 조건을 확인함','verified','checkbox')}{field('판매 · 사용 가능','active','checkbox')}<label className="field">미디어 종류<select value={modal.mediaType} onChange={e=>setModal({...modal,mediaType:e.target.value})}><option>TEXT</option><option>IMAGE</option><option>VIDEO</option></select></label>{field('공개 HTTPS 미디어 주소 (이미지·영상)','mediaUrl')}{field('미디어 출처 · 사용 권한','mediaRights','textarea')}{field('대체 텍스트','alt')}</>}
 {modal.type==='plan'&&<>{selectAccount()}{field('시작 날짜','date','date',{required:true})}{field('준비할 날짜 수 (3일 = 9개)','days','number',{min:1,max:3})}<p className="hint">등록된 주제와 검증된 상품에서 소재를 선택합니다. 계정의 자동 승인 설정이 꺼져 있으면 검토 대기로 저장합니다. 이미 사용한 슬롯은 건너뜁니다.</p></>}
 {modal.type==='import'&&<>{selectAccount()}{field('첫 예약 날짜','date','date',{required:true})}<label className="field">입력 형식<select value={modal.format} onChange={e=>setModal({...modal,format:e.target.value})}><option value="text">일상글 텍스트 (---로 구분)</option><option value="json">JSON (본문 · 답글 · 상품)</option></select></label>{field('글 내용','content','textarea',{required:true,rows:12,placeholder:modal.format==='json'?'[{"body":"본문", "replies":["답글"], "productId":"상품 ID (선택)"}]':'첫 번째 글\n---\n두 번째 글'})}<p className="hint">등록한 글은 검토 후 승인해야 예약됩니다. 상품 ID가 있는 글은 등록된 고지와 링크를 적용합니다.</p></>}
 {modal.type==='rewrite'&&<><p className="hint">같은 주제로 다른 도입과 전개를 만듭니다. 본문은 150자 내외이며, 새 글은 다시 검토해야 합니다. 성공한 다시쓰기 {modal.rewriteCount||0}/5회 · 생성 호출 한도 적용</p><div className="rewrite-original">{modal.body}</div>{field('바꾸고 싶은 점 (선택)','feedback','textarea',{maxLength:1000,placeholder:'예: 대화로 시작하고 마지막은 질문 없이 끝내줘. 생활정보를 짧은 이야기로 풀어줘.'})}</>}
 {modal.type==='edit'&&<>{field('본문','body','textarea',{rows:8,maxLength:500})}{field('자기 답글 (여러 개는 줄 사이 ---로 구분)','replyText','textarea',{rows:8})}<p className="hint">수정하면 기존 승인이 해제되고 다시 검증합니다.</p></>}
 {modal.type==='settings'&&<>{field('공통 Gemini API 키 (.env 미사용 시, 빈칸이면 유지)','geminiKey','password',{autoComplete:'new-password'})}<p className="hint">두 프로필 공통 설정입니다. .env에 GEMINI_API_KEY를 입력하고 재시작하면 적용됩니다. 환경 키가 있으면 아래 저장 키보다 우선합니다.<br/>모델은 자동 선택합니다. Gemini 모델 오류 시 다른 지원 모델을 시도하고, 대체 사용이 켜져 있으면 GPT로 이어갑니다.</p>{field('Gemini 장애 시 GPT 대체 사용','fallback','checkbox')}{field('전체 하루 생성 요청 한도','dailyCalls','number',{min:0})}{field('Threads 앱 ID','appId')}{field('Threads 앱 시크릿 (빈칸이면 유지)','appSecret','password',{autoComplete:'new-password'})}<p className="hint">OAuth 리디렉션 주소: {window.location.origin}/oauth/callback<br/>키를 저장한 뒤 연결 시험을 실행하세요. GPT는 터미널의 codex login으로 ChatGPT 로그인하세요.</p></>}
 </div><div className="modal-footer"><button type="button" onClick={()=>setModal(null)}>닫기</button><button className="primary" disabled={busy} type="submit">{busy?'처리 중…':modal.type==='plan'?'글 생성 시작':modal.type==='rewrite'?'AI 다시쓰기':'저장'}</button></div></form></section></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
